"""
TempMail Harvester - Provider Definitions
Contains 220+ disposable/temporary email providers.
Organized into API-based providers and domain-based providers.
"""

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# API-BASED PROVIDERS (Services with REST API endpoints)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

API_PROVIDERS = [
    {
        "name": "1secmail",
        "url": "https://www.1secmail.com",
        "api_endpoint": "https://www.1secmail.com/api/v1/?action=genRandomMailbox&count=5",
        "method": "GET",
        "parser": "json_array",
    },
    {
        "name": "GuerrillaMail",
        "url": "https://www.guerrillamail.com",
        "api_endpoint": "https://api.guerrillamail.com/ajax.php?f=get_email_address&ip=127.0.0.1",
        "method": "GET",
        "parser": "guerrilla",
    },
    {
        "name": "Mail.tm",
        "url": "https://mail.tm",
        "api_endpoint": "https://api.mail.tm/domains",
        "method": "GET",
        "parser": "mail_tm_domains",
    },
    {
        "name": "Mail.gw",
        "url": "https://mail.gw",
        "api_endpoint": "https://api.mail.gw/domains",
        "method": "GET",
        "parser": "mail_tm_domains",
    },
    {
        "name": "Tempmail.lol",
        "url": "https://tempmail.lol",
        "api_endpoint": "https://api.tempmail.lol/v2/inbox/create",
        "method": "GET",
        "parser": "tempmail_lol",
    },
    {
        "name": "Emailfake.com",
        "url": "https://emailfake.com",
        "api_endpoint": "https://emailfake.com/fake_email_generator",
        "method": "GET",
        "parser": "html_email_extract",
    },
]

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DOMAIN-BASED PROVIDERS
# Known disposable email domains - we generate random addresses
# using these domains. Each entry = one provider.
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISPOSABLE_DOMAINS = [
    # --- 1secmail family ---
    "1secmail.com",
    "1secmail.org",
    "1secmail.net",
    "bheps.com",
    "dcctb.com",
    "kzccv.com",
    "qiott.com",
    "wuuvo.com",
    "esiix.com",
    "wwjmp.com",
    # --- GuerrillaMail family ---
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamail.de",
    "guerrillamail.info",
    "guerrillamail.biz",
    "guerrillamailblock.com",
    "grr.la",
    "sharklasers.com",
    "pokemail.net",
    "spam4.me",
    # --- YOPmail family ---
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    # --- Mailinator family ---
    "mailinator.com",
    "maildrop.cc",
    "dispostable.com",
    # --- Temp-Mail variants ---
    "tempail.com",
    "temp-mail.org",
    "temp-mail.io",
    "tempmailo.com",
    "tempinbox.com",
    "tmpmail.net",
    "tmpmail.org",
    # --- Trashmail family ---
    "trashmail.com",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashmail.at",
    "trashmail.ws",
    "trashmailer.com",
    "trashymail.com",
    "trashymail.net",
    "trashdevil.com",
    "trashdevil.de",
    # --- Throwaway/Generator ---
    "throwaway.email",
    "tempr.email",
    "generator.email",
    "fakemail.net",
    "fakeinbox.com",
    "crazymailing.com",
    # --- Privacy/Anon ---
    "mohmal.com",
    "minutemail.com",
    "discard.email",
    "mailcatch.com",
    "spamgourmet.com",
    "mytemp.email",
    "harakirimail.com",
    "mailnesia.com",
    "anonymbox.com",
    "mailnull.com",
    "spamhole.com",
    "spamfree24.org",
    # --- Incognito/Inbox ---
    "incognitomail.com",
    "incognitomail.net",
    "inboxalias.com",
    "inboxclean.com",
    "inboxclean.org",
    # --- German disposable ---
    "wegwerfmail.de",
    "wegwerfmail.net",
    "wegwerfmail.org",
    # --- Get* family ---
    "getairmail.com",
    "getonemail.com",
    "getonemail.net",
    "getnada.com",
    # --- Disposable* family ---
    "devnullmail.com",
    "disposableaddress.com",
    "disposableemails.com",
    "disposableinbox.com",
    "dispose.it",
    # --- Don't/Dump family ---
    "dontreg.com",
    "dontsendmespam.de",
    "dump-email.info",
    "dumpandjunk.com",
    "dumpmail.de",
    "dumpyemail.com",
    # --- Email* family ---
    "emailias.com",
    "emailigo.de",
    "emailinfive.com",
    "emailmiser.com",
    "emailsensei.com",
    "emailtemporario.com.br",
    "emailwarden.com",
    "emaildienst.de",
    "emailgo.de",
    "emailproxsy.com",
    "emailto.de",
    "email60.com",
    "emailisvalid.com",
    # --- Etranquil family ---
    "etranquil.com",
    "etranquil.net",
    "etranquil.org",
    # --- Fast* car family ---
    "fastacura.com",
    "fastchevy.com",
    "fastchrysler.com",
    "fastkawasaki.com",
    "fastmazda.com",
    "fastmitsubishi.com",
    "fastnissan.com",
    "fastsubaru.com",
    "fastsuzuki.com",
    "fasttoyota.com",
    # --- F*mail family ---
    "filzmail.com",
    "fizmail.com",
    # --- Misc E ---
    "ephemail.net",
    "eyepaste.com",
    "explodemail.com",
    "emz.net",
    "enterto.com",
    "evopo.com",
    "easytrashmail.com",
    "einrot.com",
    # --- Misc B-C ---
    "binkmail.com",
    "bobmail.info",
    "chammy.info",
    "boximail.com",
    "byom.de",
    "cashette.com",
    "chacuo.net",
    "cubiclink.com",
    "curryworld.de",
    "cust.in",
    "cool.fr.nf",
    "clipmail.eu",
    "coldemail.info",
    # --- Misc D ---
    "dacoolone.com",
    "daintly.com",
    "dandikmail.com",
    "dayrep.com",
    "deadaddress.com",
    "dingbone.com",
    # --- Misc G-I ---
    "great-host.in",
    "gsrv.co.uk",
    "gishpuppy.com",
    "haltospam.com",
    "hotpop.com",
    "ichimail.com",
    "imails.info",
    # --- Misc J-K ---
    "jetable.org",
    "dodgeit.com",
    "dodgit.com",
    "dodsi.com",
    # --- e4ward ---
    "e4ward.com",
    # --- Fake family ---
    "fakeinformation.com",
    "fakemail.fr",
    "fakemailgenerator.com",
    # --- Spam* family ---
    "spambob.com",
    "spambob.net",
    "spambob.org",
    "spambog.com",
    "spambog.de",
    "spambog.ru",
    "spamcannon.com",
    "spamcannon.net",
    "spamcero.com",
    "spamcon.org",
    "spamcowboy.com",
    "spamcowboy.net",
    "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    # --- NoSpam family ---
    "nospam.ze.tc",
    "nobulk.com",
    "noclickemail.com",
    "nogmailspam.info",
    "nomail.xl.cx",
    "nomail2me.com",
    "nomorespamemails.com",
    "nostamp.com",
    "nospamfor.us",
    # --- Mail* extended ---
    "mailblocks.com",
    "mailbucket.org",
    "maileater.com",
    "mailexpire.com",
    "mailfreeonline.com",
    "mailimate.com",
    "mailin8r.com",
    "mailinater.com",
    "mailincubator.com",
    "mailismagic.com",
    "mailmoat.com",
    "mailnator.com",
    "mailquack.com",
    "mailscrap.com",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailzilla.com",
    "mailsac.com",
    "meltmail.com",
    # --- Additional domains to reach 220+ ---
    "sogetthis.com",
    "soodonims.com",
    "tempsky.com",
    "thankyou2010.com",
    "thisisnotmyrealemail.com",
    "throwam.com",
    "tittbit.in",
    "tmail.ws",
    "toiea.com",
    "topranklist.de",
    "turual.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "upliftnow.com",
    "uplipht.com",
    "venompen.com",
    "veryreallyfakeemails.com",
    "viditag.com",
    "viewcastmedia.com",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "wasteland.rfc822.org",
    "webemail.me",
    "weetransfert.com",
    "whyspam.me",
    "wickmail.net",
    "wilemail.com",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "wwwnew.eu",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xjoi.com",
    "xoxy.net",
    "yapped.net",
    "yep.it",
    "yogamaven.com",
    "yuurok.com",
    "zehnminutenmail.de",
    "zippymail.info",
    "zoaxe.com",
    "zoemail.org",
]


def get_total_provider_count():
    """Return total number of providers (API + Domain-based)."""
    return len(API_PROVIDERS) + len(DISPOSABLE_DOMAINS)
